version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo-area
    ports:
      - "27017:27017"
    networks:
      - area-network
  # server:
  #   build:
  #     context: ./back-end
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: back-area
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - area-network
  # # Add mobile service
  # client_web:
  #   build:
  #     context: ./front-end
  #     dockerfile: Web-Dockerfile
  #   restart: always
  #   container_name: front-area
  #   ports:
  #     - "8081:3000"
  #   networks:
  #     - area-network
  #   depends_on:
  #     - server
  #     # Add mobile dependency

volumes:
  front-data:
networks:
  area-network:
