name: Check if the docker build

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - AREA-58*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d
        sleep 180 # Give some time for services to start (adjust as needed)

    - name: Check if services are running
      run: |
        docker ps -a
        docker-compose ps

    - name: Clean up
      run: docker-compose down